# Generated by Django 3.1.7 on 2021-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
